### ISSUE TITLE
Bug: no output

### ISSUE THREAD

**Issue by waldekmastykarz** [StfBauer/markshell#18] opened 2020-08-31 17:33 UTC
Version: 0.0.6-beta3

Markshell: https://github.com/waldekmastykarz/cli-microsoft365/blob/552d9fd2b83f8c3487e1d8b274b4965b6275ec78/docs/manual/docs/cmd/spo/site/site-list.md

Expected: markshelled output

Actual: no output

**Comment by StfBauer** [comment] 2020-08-31 18:19
The no output is caused by the following line:

> command
> spo site list

And fails with the following error.
<img width="539" alt="image" src="https://user-images.githubusercontent.com/5503835/91752676-ff72ff80-ebc6-11ea-8c11-860125a2df38.png">

command support is added in next drop. 👍

**Comment by StfBauer** [comment] 2020-09-01 07:21
`command` missing is fixed in 📦  markshell@0.0.6-beta5

**Comment by alexlemaire** [comment] 2020-09-01 10:37
I've just got a similar issue there:

![image](https://user-images.githubusercontent.com/50198634/91839677-bf0b9400-ec4f-11ea-80ed-68343d3104ee.png)

**Comment by StfBauer** [comment] 2020-09-01 12:50
@alexlemaire you don't have any language specified that is why you get this issue.

Good Catch - The only change I can address this does not highlight the code at all.

**Comment by alexlemaire** [comment] 2020-09-01 13:23
Alright I see now, thanks for your reactivity!

> Good Catch - The only change I can address this does not highlight the code at all.

In my specific case having `markshell` not highlight the code if nothing is specified would fit perfectly.

Or/and a global setting for `markshell` to specify a preferred default language. But that may be too restrictive/error prone...

**Comment by StfBauer** [comment] 2020-09-01 14:30
It won't work that way because what is the preferred language if you have HTML, CSS, SASS and JavaScript on the same page.

In fact, GitHub doesn't highlight that code either, why put it in a code block anyway in the first place, when there is no benefit on specifying the language?

**Comment by waldekmastykarz** [comment] 2020-09-01 14:57
I'd agree with treating code block without language as plain-text without any highlighting.

**Comment by StfBauer** [comment] 2020-09-01 15:10
That is one and the same ;)

**Comment by StfBauer** [comment] 2020-09-01 20:22
Don't throw any exception any more and smooth highlight the code like this now:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/5503835/91902122-84cae280-eca1-11ea-9dad-cbbec6267eb1.png">

First one is without any language.
Second one javascript
Third typescript

**Comment by StfBauer** [comment] 2020-09-01 20:31
Fixed in - 0.0.6-beta6

**Comment by alexlemaire** [comment] 2020-09-02 10:12
I've just tried the new package version. No error anymore but when using `markshell.toConsole(pathToMyMarkdown)` it now outputs `null` into the console.

I cross-checked with `fs.readFileSync` using the same path and the file prints out. `markshell.toRawContent` works also fine.

**Comment by StfBauer** [comment] 2020-09-02 10:37
@alexlemaire added now your readme file to my test. I will let you know where it is broken.

**Comment by StfBauer** [comment] 2020-09-02 10:45
@alexlemaire Thanks for your readme - found issue and fixed it in   markshell@0.0.7-beta7

**Comment by alexlemaire** [comment] 2020-09-02 11:02
Awesome!

Another small thing I noticed: it looks like in code blocks and inline code, all `_` characters are getting removed.

Here are 2 screenshots to see the difference between the raw markdown and the one getting printed:

**raw**
![image](https://user-images.githubusercontent.com/50198634/91973183-16773600-ed1c-11ea-960b-8511eb3abd7f.png)

**printed**
![image](https://user-images.githubusercontent.com/50198634/91973274-432b4d80-ed1c-11ea-8a03-c2c3563591d1.png)

I'm not sure whether this should still continue in this issue or if you would like me to open another one maybe? (since it's not anymore linked to a _no output_ issue)

**Comment by StfBauer** [comment] 2020-09-02 17:03
Another update is out - that should fix this issue too: version 0.0.8

**Comment by alexlemaire** [comment] 2020-09-03 09:48
Thanks a lot for the follow-up!

I think this might be related to the new fix: when using underscore `_` to create italic text in markdown, the underscores are also printed out (examples below).

**raw**
![image](https://user-images.githubusercontent.com/50198634/92099623-083c1f00-eddb-11ea-82c2-6fedc41f4395.png)

**printed**
![image](https://user-images.githubusercontent.com/50198634/92099672-14c07780-eddb-11ea-9041-0f7fe8570fc0.png)

**Comment by StfBauer** [comment] 2020-09-03 19:48
0.0.9 should fix this. Thanks for finding this small issues @alexlemaire

**Closed** 2020-09-07 20:23 UTC
Labels: bug
